services:
  selenium:
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"
    shm_size: 2g
    
  app:
    build: .
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
      - SE_DISABLE_MANAGER=true
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    depends_on:
      - selenium 